#!/usr/bin/env python3
"""A second implementation of B-Called℠ v2, written from SPEC.md Part II alone, in Python's
standard library — no import of, and no line copied from, the TypeScript.

Why it exists: v2's vectors are generated by v2's own code, so on their own they prove only
that the code agrees with itself. If this independent port reproduces every vector, the SPEC
is sufficient to build a conforming implementation, and a disagreement between spec and code
cannot hide. Then it breaks the algorithm the ways a porter most often does and requires each
break to be CAUGHT — a check that has only ever passed is an untested claim.

Run: python3 scripts/port_check.py        (exit 0 = conforms, and every control failed)
"""
import hashlib
import hmac
import json
import sys
from pathlib import Path

VECTORS = json.loads((Path(__file__).resolve().parent.parent / "vectors" / "b-called-v2-vectors.json").read_text())


# ── the spec, Part II ──────────────────────────────────────────────────────────────────────
def u32(n):
    return n.to_bytes(4, "big")


def u64(n):
    return n.to_bytes(8, "big")


def field(b):
    return u32(len(b)) + b


def s(text):
    return field(text.encode("utf-8"))


def roster_list(ids):
    return u32(len(ids)) + b"".join(s(i) for i in ids)


def commitment(inp, *, omit_round=False):
    form = inp["form"]
    parts = [s("called-draw/v2/commitment"), s(inp["network"].lower())]
    if not omit_round:
        parts.append(u64(inp["round"]))
    parts += [
        s(inp["drawId"]),
        s(form),
        s(inp["regime"]),
        field(bytes.fromhex(inp["salt"])),
        roster_list(inp["roster"]),
        s((inp.get("previousLast") or "") if form == "turn" else ""),
        u32(inp["admit"] if form == "lot" else 0),
    ]
    return hashlib.sha256(b"".join(parts)).hexdigest()


def stream(key, label, *, little_endian=False):
    sk = hmac.new(key, s("called-draw/v2/stream") + s(label), hashlib.sha256).digest()
    counter = 0
    while True:
        block = hmac.new(sk, u64(counter), hashlib.sha256).digest()
        counter += 1
        for o in range(0, 32, 4):
            yield int.from_bytes(block[o:o + 4], "little" if little_endian else "big")


def uniform(it, m):
    limit = 2**32 - (2**32 % m)
    while True:
        x = next(it)
        if x < limit:
            return x % m


def draw(inp, randomness, *, rotate_boundary=False, omit_round=False):
    c = commitment(inp, omit_round=omit_round)
    key = hashlib.sha256(
        s("called-draw/v2/key") + field(bytes.fromhex(c)) + field(bytes.fromhex(randomness)) + field(bytes.fromhex(inp["salt"]))
    ).digest()
    it = stream(key, "order")
    order = list(inp["roster"])
    for i in range(len(order) - 1, 0, -1):
        j = uniform(it, i + 1)
        order[i], order[j] = order[j], order[i]
    swapped = False
    prev = inp.get("previousLast")
    if inp["form"] == "turn" and prev is not None and len(order) > 1 and order[0] == prev:
        if rotate_boundary:  # v1's rule — must NOT match
            order.append(order.pop(0))
        else:
            j = 1 + uniform(it, len(order) - 1)
            order[0], order[j] = order[j], order[0]
        swapped = True
    out = {"commitment": c, "order": order}
    if inp["form"] == "lot":
        out["admitted"] = order[: inp["admit"]]
    else:
        out["boundarySwapped"] = swapped
    return out


# ── the check ──────────────────────────────────────────────────────────────────────────────
failures = []
checked = 0


def expect(cond, what):
    global checked
    checked += 1
    if not cond:
        failures.append(what)


def draw_cases():
    cases = VECTORS["cases"]
    for r in cases["season_public_turns"]["rounds"]:
        yield f"season round {r['input']['round']}", r
    for key in ("turn_boundary_swap", "turn_sealed", "lot_admit_0", "lot_admit_3", "lot_admit_10"):
        yield key, cases[key]


for rnd, beacon in VECTORS["rounds"].items():
    expect(hashlib.sha256(bytes.fromhex(beacon["signature"])).hexdigest() == beacon["randomness"], f"round {rnd}: randomness != SHA-256(signature)")

n_draws = 0
for name, case in draw_cases():
    got = draw(case["input"], case["randomness"])
    for k in ("commitment", "order", "admitted", "boundarySwapped"):
        if k in case or k in got:
            expect(got.get(k) == case.get(k), f"{name}: {k} differs — port {got.get(k)} vs vector {case.get(k)}")
    n_draws += 1

# The season's chaining: each round's previousLast is the previous round's closer.
rounds = VECTORS["cases"]["season_public_turns"]["rounds"]
for a, b in zip(rounds, rounds[1:]):
    expect(b["input"]["previousLast"] == a["order"][-1], f"season chaining broken at round {b['input']['round']}")

st = VECTORS["cases"]["stream"]
it = stream(bytes.fromhex(st["key"]), st["label"])
expect([next(it) for _ in st["uint32"]] == st["uint32"], "stream uint32 differs")

rt = VECTORS["cases"]["round_time"]
chain = VECTORS["chain"]
expect(chain["genesisTime"] + (rt["round"] - 1) * chain["period"] == rt["unixSeconds"], "round time differs")

# Rejection sampling, scripted: 2^32-1 must be rejected for m = 3.
expect(uniform(iter([0xFFFFFFFF, 5]), 3) == 2, "rejection sampling did not reject 0xFFFFFFFF for m=3")

# ── known-failure controls: each broken port MUST disagree with the vectors ──────────────────
controls = []
bs = VECTORS["cases"]["turn_boundary_swap"]
controls.append(("v1's rotation at the boundary", draw(bs["input"], bs["randomness"], rotate_boundary=True)["order"] != bs["order"]))
lot3 = VECTORS["cases"]["lot_admit_3"]
controls.append(("a commitment that omits the round", draw(lot3["input"], lot3["randomness"], omit_round=True)["commitment"] != lot3["commitment"]))
it_le = stream(bytes.fromhex(st["key"]), st["label"], little_endian=True)
controls.append(("little-endian stream decoding", [next(it_le) for _ in st["uint32"]] != st["uint32"]))
controls.append(("modulo with no rejection", (0xFFFFFFFF % 3) != uniform(iter([0xFFFFFFFF, 5]), 3)))
tampered = dict(lot3["input"], admit=4)
controls.append(("a lot whose admit count changed after commit", commitment(tampered) != lot3["commitment"]))
for what, caught in controls:
    expect(caught, f"CONTROL NOT CAUGHT: {what}")

if n_draws < 7:
    failures.append(f"only {n_draws} draw cases were checked — the vectors file lost cases")

if failures:
    print(f"port_check: {len(failures)} FAILURE(S) of {checked} checks")
    for f in failures:
        print("  ✗", f)
    sys.exit(1)
print(f"port_check: {checked} checks passed — {n_draws} draws reproduced from the spec alone; {len(controls)} broken ports all caught")
